[package]
name = "libsecp256k1"
description = "Pure Rust secp256k1 implementation."
license = "Apache-2.0"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]

[lib]
name = "secp256k1"

[dependencies]
