[package]
name = "schnorr"
version = "0.1.0"
authors = ["CjS77 <cayle.sharrock@gmail.com>"]

[dependencies]
secp256k1 = { path = "../secp256k1" }
rand = { version = "0.4", default-features = false }
sha2 = "0.6"
arrayref = "0.3"
